spring:
  application:
    name: java-server
  data:
    mongodb:
      uri: mongodb://admin:testtest@localhost:27017/pokemon?authSource=admin
  webflux:
    base-path: /
    
server:
  port: 3000
  
logging:
  level:
    root: INFO
    com.pokemon: DEBUG
